### PR TITLE
Create 简体中文

### PR DESCRIPTION
**Pull request by 3Qyou**
Can I add the language of my country? If I can, I will thank you very much! My English is not very good, I'm sorry. I don't know whether my translated text can take effect, because I haven't done this type of translation before, but I just found the JSON suffix file in cheatmenu/locale.

### CODE REVIEW

**Comment by 3Qyou** [comment]
I just registered this website and am not familiar with it. If there is any wrong operation, please forgive me!

**Comment by user-grinch** [comment]
Hello there, I appreciate your work and I'll be sure to take a look and add it soon. However the current locale file that you provided appears to be outdated. I'd highly appreciate if you base your work on a recent version of the language file (resources/common/locale/English.toml).

**Comment by 3Qyou** [comment]
Thank you very much. I will download the latest version of the text and re translate it, because there is basically no built-in modifier of VC in my place of residence. I am very excited to see your work! Thank you for your contribution to this game! Thank you！

**Comment by 3Qyou** [comment]
I retranslated the latest version of the text. I really hope to see the language of my country soon. Can I advertise this modifier on the video platform after the update? I will indicate the author, the ownership of the author and the original address of this modifier. I hope you can agree. My English is not very good, if there are some grammatical errors, please forgive me! I really mean no harm.

**Comment by user-grinch** [comment]
You're free to show the menu wherever you'd like. I don't know when the stable version is gonna come out but it should work from next betas.

**Review by user-grinch — COMMENTED** [review]
Few minor corrections are needed,
1. The language file should be inside the `resource/common/locale/` directory (Where the `English.toml` file is)
2. The file name needs to have a `.toml` extension.
3. The headers (The texts inside `[ ]`) should be in English
4. I think you have missed some of the texts

**Comment by 3Qyou** [comment]
I'm sorry, it's my first time to participate in translation, which has caused you a little trouble. I have corrected it again. Because my English is not very good, some texts have not been translated. I don't know if I can upload some of them in the way of translation, and keep the rest in the original.

**Comment by user-grinch** [comment]
Thanks for your work!

**Comment by 3Qyou** [comment]
> 感谢您的工作！

I'm really happy to pass, but how can I get the version that supports my national language? The version I get on this website is still the last version, which only supports English and Spanish. I don't know what to do.

**Comment by user-grinch** [comment]
> > 感谢您的工作！
> 
> I'm really happy to pass, but how can I get the version that supports my national language? The version I get on this website is still the last version, which only supports English and Spanish. I don't know what to do.

I haven't yet released the version yet. But when I do it'll be on the discord server. Join there if you'd like.

**Comment by 3Qyou** [comment]
> > > 感谢您的工作！
> > 
> > 
> > 我真的很高兴通过，但是我怎样才能获得支持我的国家语言的版本？我在这个网站上得到的版本仍然是最后一个版本，它只支持英语和西班牙语。我不知道该怎么办。
> 
> 我还没有发布版本。但是当我这样做时，它将在不和谐服务器上。如果您愿意，可以加入那里。

How long will it take before the next version is released?

**Comment by user-grinch** [comment]
> > > > 感谢您的工作！
> > > 
> > > 
> > > 我真的很高兴通过，但是我怎样才能获得支持我的国家语言的版本？我在这个网站上得到的版本仍然是最后一个版本，它只支持英语和西班牙语。我不知道该怎么办。
> > 
> > 
> > 我还没有发布版本。但是当我这样做时，它将在不和谐服务器上。如果您愿意，可以加入那里。
> 
> How long will it take before the next version is released?

Beta - Probably in 1-2 days
Stable - No ETA (I don't have any plans for it at the moment, can take up to next year)

**Comment by 3Qyou** [comment]
> > > > > 感谢您的工作！
> > > > 
> > > > 
> > > > 我真的很高兴通过，但是我怎样才能获得支持我的国家语言的版本？我在这个网站上得到的版本仍然是最后一个版本，它只支持英语和西班牙语。我不知道该怎么办。
> > > 
> > > 
> > > 我还没有发布版本。但是当我这样做时，它将在不和谐服务器上。如果您愿意，可以加入那里。
> > 
> > 
> > 下一个版本需要多长时间才能发布？
> 
> Beta - 可能在1-2天内稳定 - 没有ETA（我目前没有任何计划，可能需要到明年）

Where will the beta version be released? Can I use it?（It's a pity if you can't, but I'll wait until the official version is released! I wish you a happy life and a smooth exam!）

**Comment by user-grinch** [comment]
> > > > > > 感谢您的工作！
> > > > > 
> > > > > 
> > > > > 我真的很高兴通过，但是我怎样才能获得支持我的国家语言的版本？我在这个网站上得到的版本仍然是最后一个版本，它只支持英语和西班牙语。我不知道该怎么办。
> > > > 
> > > > 
> > > > 我还没有发布版本。但是当我这样做时，它将在不和谐服务器上。如果您愿意，可以加入那里。
> > > 
> > > 
> > > 下一个版本需要多长时间才能发布？
> > 
> > 
> > Beta - 可能在1-2天内稳定 - 没有ETA（我目前没有任何计划，可能需要到明年）
> 
> Where will the beta version be released? Can I use it?（It's a pity if you can't, but I'll wait until the official version is released! I wish you a happy life and a smooth exam!）

Beta is usually released on the [discord server](https://discord.com/invite/ZzW7kmf). I still have some fixes to do before I release the beta though. Likely tomorrow or the day after.

**Comment by user-grinch** [comment]
> > > > > > > > 感谢您的工作！
> > > > > > > 
> > > > > > > 
> > > > > > > 我真的很高兴通过，但是我怎样才能获得支持我的国家语言的版本？我在这个网站上得到的版本仍然是最后一个版本，它只支持英语和西班牙语。我不知道该怎么办。
> > > > > > 
> > > > > > 
> > > > > > 我还没有发布版本。但是当我这样做时，它将在不和谐服务器上。如果您愿意，可以加入那里。
> > > > > 
> > > > > 
> > > > > 下一个版本需要多长时间才能发布？
> > > > 
> > > > 
> > > > Beta - 可能在1-2天内稳定 - 没有ETA（我目前没有任何计划，可能需要到明年）
> > > 
> > > 
> > > 测试版将在哪里发布？我可以使用它吗？（如果你不能，那真是太可惜了，但我会等到正式版发布！祝您生活愉快，考试顺利！
> > 
> > 
> > Beta 版通常在[不和谐服务器上](https://discord.com/invite/ZzW7kmf)发布。不过，在我发布测试版之前，我还有一些修复工作要做。可能是明天或后天。
> 
> Well, thank you very much.

Just finished today, [here](https://cdn.discordapp.com/attachments/899251596863610980/1004824253587271700/CheatMenuSA.7z)

**Comment by 3Qyou** [comment]
> > > > > > > > > 感谢您的工作！
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我真的很高兴通过，但是我怎样才能获得支持我的国家语言的版本？我在这个网站上得到的版本仍然是最后一个版本，它只支持英语和西班牙语。我不知道该怎么办。
> > > > > > > 
> > > > > > > 
> > > > > > > 我还没有发布版本。但是当我这样做时，它将在不和谐服务器上。如果您愿意，可以加入那里。
> > > > > > 
> > > > > > 
> > > > > > 下一个版本需要多长时间才能发布？
> > > > > 
> > > > > 
> > > > > Beta - 可能在1-2天内稳定 - 没有ETA（我目前没有任何计划，可能需要到明年）
> > > > 
> > > > 
> > > > 测试版将在哪里发布？我可以使用它吗？（如果你不能，那真是太可惜了，但我会等到正式版发布！祝您生活愉快，考试顺利！
> > > 
> > > 
> > > Beta 版通常在[不和谐服务器上](https://discord.com/invite/ZzW7kmf)发布。不过，在我发布测试版之前，我还有一些修复工作要做。可能是明天或后天。
> > 
> > 
> > 好吧，非常感谢。
> 
> 今天刚完成，[在这里](https://cdn.discordapp.com/attachments/899251596863610980/1004824253587271700/CheatMenuSA.7z)

I don't know why. If you change to Chinese, you will see "??" The language cannot be displayed.

**Comment by user-grinch** [comment]
On first attempt that should be the case. But there should be a option to download the font from the menu when you set it to chinese.

**Comment by 3Qyou** [comment]
> 在第一次尝试时，情况应该如此。但是，当您将其设置为中文时，应该有一个选项可以从菜单中下载字体。

Yes, but there is no pop-up window or progress bar after clicking, and there is no jump to any web page. I don't know how to install this supported font (after clicking, I waited for a few minutes, but the font still displayed "??"）

**Comment by user-grinch** [comment]
You did use the new files that came with CheatMenuSA folder right? would be better if you can send a screenshot of your window after changing to chinese.

**Comment by 3Qyou** [comment]
> 您确实使用了CheatMenuSA文件夹附带的新文件吗？如果您可以在更改为中文后发送窗口的屏幕截图，那就更好了。



> discord server

Sorry, I didn't use SA to test, I used VC. After I downloaded the beta version of discord server 8 / 5, the situation is as described above. Is the shortcut key of SA cheating menu the same as that of VC? I don't know why I can't open the cheat menu with SA test
QQ图片20220808162803
.

**Comment by user-grinch** [comment]
Yes, it's the same. I only sent you the updated menu for SA, why did you test on VC lol

**Comment by 3Qyou** [comment]
> 是的，这是一样的。我只向您发送了SA的更新菜单，为什么您在VC上进行测试哈哈

Hahaha, because I found the cheat menu on the modifier page of VC at the beginning. I have just tested in SA and found that some text translation errors need to be improved. I will continue to improve it. Will this cheating Chinese synchronize III and VC in the future? I want to focus on the translation errors of the trilogy and revise it together.

**Comment by user-grinch** [comment]
> translation errors need to b

They, already do. Here are the VC and III versions if you're interested in them.
[VC](https://cdn.discordapp.com/attachments/899251596863610980/1004824254006706176/CheatMenuVC.7z)
[III](https://cdn.discordapp.com/attachments/899251596863610980/1004824253205581944/CheatMenuIII.7z)

**Comment by 3Qyou** [comment]
> > translation errors need to b
> 
> They, already do. Here are the VC and III versions if you're interested in them. [VC](https://cdn.discordapp.com/attachments/899251596863610980/1004824254006706176/CheatMenuVC.7z) [III](https://cdn.discordapp.com/attachments/899251596863610980/1004824253205581944/CheatMenuIII.7z)

Hi, do you remember me? I have perfected the Chinese translation again. I want to upload the update, but I don't know where to upload it. Can you help me?

**Comment by user-grinch** [comment]
> > > translation errors need to b
> > 
> > 
> > They, already do. Here are the VC and III versions if you're interested in them. [VC](https://cdn.discordapp.com/attachments/899251596863610980/1004824254006706176/CheatMenuVC.7z) [III](https://cdn.discordapp.com/attachments/899251596863610980/1004824253205581944/CheatMenuIII.7z)
> 
> Hi, do you remember me? I have perfected the Chinese translation again. I want to upload the update, but I don't know where to upload it. Can you help me?

Make another pull request.

**Pull request merged**
